export const ROUTES = {
  HOME: "/",
  PRODUCTS: "/menu",
  MENU: "/menu",
  /** Alias — cùng đường dẫn sản phẩm */
  SHOP: "/menu",
  CART: "/cart",
  CHECKOUT: "/checkout",
  LOGIN: "/login",
  PROFILE: "/profile",
  ORDERS: "/orders",
  ORDER_DETAIL: (id: string) => `/orders/${id}`,
  ADDRESSES: "/profile/addresses",
  NOTIFICATIONS: "/notifications",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  VERIFY_EMAIL: "/verify-email",
  VERIFY_OTP: "/verify-otp",
  TERMS: "/terms",
  PRIVACY: "/privacy",
  FEEDBACK: "/feedback",
  PROMOTIONS: "/promotions",
  VOUCHERS: "/vouchers",
  REFERRAL: "/referral",
  ABOUT: "/about",
  LOYALTY_PAGE: "/loyalty",
  LOYALTY: (code: string) => `/loyalty?code=${encodeURIComponent(code)}`,
  REWARDS: "/rewards",
  GROUP_ORDERS: "/group-order",
  GROUP_ORDER: (token: string) => `/group-order/${token}`,
  BLOG: "/blog",
  BLOG_POST: (slug: string) => `/blog/${slug}`,
} as const;
