export const env = {
  API_URL: process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:5000",
  GOOGLE_CLIENT_ID: process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID ?? "",
  SITE_URL: process.env.NEXT_PUBLIC_SITE_URL ?? "",
  CLOUDINARY_CLOUD_NAME: process.env.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME ?? "",
  CLOUDINARY_UPLOAD_PRESET: process.env.NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET ?? "",
};
